{{- range .Values.dockerRegistries }}
{{- $dockerRegistry := . -}}
{{- range $namespace := $dockerRegistry.namespaces }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: "pull-secret-{{- $dockerRegistry.name }}"
  namespace: {{ $namespace | quote }}
data:
  .dockerconfigjson: {{ $dockerRegistry.dockerconfigjson | quote }}
{{ end }}
{{ end }}